# oca-lib.sh — shared OCA catalog helpers for odoo-nix.
#
# Sourced by the scaffolder (odoo-init) and the in-project `odoo-add-module` script.
# Requires the environment variable OCA_DATASET to point at oca-modules.json
# (both callers bake the vendored data/oca-modules.json store path into it).
#
# Provides:
#   oca_repo_url <repo>                 -> https git URL for an OCA repo
#   oca_resolve_repos <series> <mod>... -> deduped, sorted repo names (closure)
#   oca_pick_modules <series>           -> interactively chosen module names
#
# Python dependencies are resolved by uv from each module's whool metadata; the
# uv path-sources in pyproject.toml are generated by lib/oca_sources.py, not here.

oca_repo_url() {
  printf 'https://github.com/OCA/%s.git\n' "$1"
}

# Transitive closure of OCA repos for a set of seed module names, within one
# Odoo series. BFS over `depends`; a dep that is not an in-series OCA module is
# Odoo core (satisfied by OCB) and is skipped. Cycles terminate via a seen set.
# Prints the deduped, sorted repo names (one per line).
oca_resolve_repos() {
  local series="$1"; shift
  local seeds_json
  seeds_json="$(printf '%s\n' "$@" | jq -R . | jq -s 'map(select(length > 0))')"
  jq -r --arg series "$series" --argjson seeds "$seeds_json" '
    [ .[] | select(.version | startswith($series + ".")) ] as $mods
    | (reduce $mods[] as $m ({}; .[$m.module] = $m.repo)) as $repo_of
    | (reduce $mods[] as $m ({}; .[$m.module] = ($m.depends // []))) as $deps_of
    | { queue: $seeds, seen: {}, repos: {} }
    | until( (.queue | length) == 0;
        .queue[0] as $cur
        | .queue |= .[1:]
        | if .seen[$cur] then .
          else
            .seen[$cur] = true
            | (if $repo_of[$cur] then .repos[$repo_of[$cur]] = true else . end)
            | .queue += ( ($deps_of[$cur] // []) | map(select($repo_of[.])) )
          end )
    | .repos | keys | sort | .[]
  ' "$OCA_DATASET"
}

# Present ALL installable modules for a series in a fuzzy gum picker; print the
# chosen bare module names. The `application` flag is only a hint (★) — most
# useful OCA modules (localizations, feature modules like repair_*) are not
# flagged as applications but are installed directly. Applications sort first.
# A TAB-separated module<TAB>label table lets us map the decorated label back to
# the bare module name. gum filter handles the ~2,500-row list with fuzzy search.
oca_pick_modules() {
  local series="$1"
  local rows
  rows="$(jq -r --arg s "$series" '
      [ .[] | select(.installable == true and (.version | startswith($s + "."))) ]
      | sort_by([(.application | not), .repo, .module])[]
      | "\(.module)\t\(if .application then "★" else " " end) \(.module)  ·  \(.repo)  ·  \((.summary // "") | gsub("\\s+"; " ") | .[0:60])"
    ' "$OCA_DATASET")"
  [ -z "$rows" ] && { echo "No installable modules for series $series." >&2; return 0; }
  local chosen
  # --no-fuzzy: match from the start of a word (predictable prefix matching)
  # instead of the loose default subsequence fuzzing. Typing a repo name (e.g.
  # "repair") surfaces all that repo's modules via the repo column.
  chosen="$(cut -f2 <<<"$rows" \
    | gum filter --no-limit --height 20 --no-fuzzy \
        --placeholder "type a module or repo name (★ = application)" \
        --header "Select OCA modules for $series  (Tab to select, Enter to confirm):" || true)"
  while IFS= read -r lbl; do
    [ -z "$lbl" ] && continue
    awk -F'\t' -v l="$lbl" '$2 == l { print $1 }' <<<"$rows"
  done <<<"$chosen"
}

# ── bundles ────────────────────────────────────────────────────────────────
# Curated, hand-maintained named sets of "must-have" module names, defined in
# data/oca-bundles.json. Requires OCA_BUNDLES to point at that file (both the
# scaffolder and the in-project odoo-add-bundle bake the store path into it).

oca_bundle_names() { jq -r 'keys[]' "$OCA_BUNDLES"; }

# Interactively choose bundles; print the chosen bare bundle names.
# A TAB-separated name<TAB>label table maps the decorated label back to the key.
oca_pick_bundles() {
  local rows chosen
  rows="$(jq -r 'to_entries[]
    | "\(.key)\t\(.key)  —  \(.value.label)  (\(.value.modules | length) modules)"' "$OCA_BUNDLES")"
  [ -z "$rows" ] && { echo "No bundles defined." >&2; return 0; }
  chosen="$(cut -f2 <<<"$rows" \
    | gum choose --no-limit \
        --header "Select OCA bundle(s) (space=toggle, enter=confirm):" || true)"
  while IFS= read -r lbl; do
    [ -z "$lbl" ] && continue
    awk -F'\t' -v l="$lbl" '$2 == l { print $1 }' <<<"$rows"
  done <<<"$chosen"
}

# Expand bundle names to their union of module names, scoped to one series.
# Bundles are series-blind, so members with no in-series catalog record are
# dropped with a warning rather than recorded and left to fail at install time.
# Prints the deduped, sorted module names (one per line).
oca_expand_bundles() {
  local series="$1"; shift
  local names=("$@") wanted=() n m
  for n in "${names[@]}"; do
    [ -z "$n" ] && continue
    if ! jq -e --arg n "$n" 'has($n)' "$OCA_BUNDLES" >/dev/null; then
      echo "  ⚠  unknown bundle: $n   (available: $(oca_bundle_names | tr '\n' ' '))" >&2
      continue
    fi
    while IFS= read -r m; do
      [ -n "$m" ] && wanted+=("$m")
    done < <(jq -r --arg n "$n" '.[$n].modules[]' "$OCA_BUNDLES")
  done
  [ "${#wanted[@]}" -eq 0 ] && return 0

  # Partition against the in-series catalog.
  local wanted_json
  wanted_json="$(printf '%s\n' "${wanted[@]}" | jq -R . | jq -s 'unique')"
  local missing
  missing="$(jq -r --arg s "$series" --argjson want "$wanted_json" '
      ([ .[] | select(.version | startswith($s + ".")) | .module ] | unique) as $have
      | $want - $have | .[]' "$OCA_DATASET")"
  if [ -n "$missing" ]; then
    echo "  ⚠  not available for $series, skipped: $(tr '\n' ' ' <<<"$missing")" >&2
  fi
  jq -r --arg s "$series" --argjson want "$wanted_json" '
      ([ .[] | select(.version | startswith($s + ".")) | .module ] | unique) as $have
      | [ $want[] | select(. as $m | $have | index($m)) ] | .[]' "$OCA_DATASET"
}
