# oca-lib.sh — shared OCA catalog helpers for odoo-nix.
#
# Sourced by the scaffolder (odoo-init) and the `odoo module add` script (lib/cli-scripts.nix).
# Requires the environment variable OCA_DATASET to point at oca-modules.json
# (both callers bake the vendored data/oca-modules.json store path into it).
#
# Provides:
#   oca_repo_url <repo>                 -> https git URL for an OCA repo
#   oca_resolve_repos <series> <mod>... -> deduped, sorted repo names (closure)
#   oca_pick_modules <series>           -> interactively chosen module names
#   oca_url_shaped <arg>                -> true if arg looks like a git URL/shorthand
#   oca_resolve_git_url <arg>           -> full git URL from a URL or owner/repo
#   oca_repo_slug <url>                 -> folder-name slug derived from a URL
#   oca_default_branch <url>            -> a remote's default branch name
#   oca_scan_modules <path>             -> module names found in a cloned repo
#   oca_pick_from_list <header>         -> interactively chosen names from stdin
#
# Python dependencies are resolved by uv from each module's whool metadata; the
# uv path-sources in pyproject.toml are generated by lib/oca_sources.py, not here.

oca_repo_url() {
  printf 'https://github.com/OCA/%s.git\n' "$1"
}

# Transitive closure of OCA repos for a set of seed module names, within one
# Odoo series. BFS over `depends`; a dep that is not an in-series OCA module is
# Odoo core (satisfied by OCB) and is skipped. Cycles terminate via a seen set.
# Prints the deduped, sorted repo names (one per line).
oca_resolve_repos() {
  local series="$1"; shift
  local seeds_json
  seeds_json="$(printf '%s\n' "$@" | jq -R . | jq -s 'map(select(length > 0))')"
  jq -r --arg series "$series" --argjson seeds "$seeds_json" '
    [ .[] | select(.version | startswith($series + ".")) ] as $mods
    | (reduce $mods[] as $m ({}; .[$m.module] = $m.repo)) as $repo_of
    | (reduce $mods[] as $m ({}; .[$m.module] = ($m.depends // []))) as $deps_of
    | { queue: $seeds, seen: {}, repos: {} }
    | until( (.queue | length) == 0;
        .queue[0] as $cur
        | .queue |= .[1:]
        | if .seen[$cur] then .
          else
            .seen[$cur] = true
            | (if $repo_of[$cur] then .repos[$repo_of[$cur]] = true else . end)
            | .queue += ( ($deps_of[$cur] // []) | map(select($repo_of[.])) )
          end )
    | .repos | keys | sort | .[]
  ' "$OCA_DATASET"
}

# ── third-party repos ─────────────────────────────────────────────────────
# Support for adding an arbitrary git repo (any host) as a submodule, not
# just OCA catalog repos. No catalog/dataset involved — everything here is
# derived from the URL/repo itself via git.

# True if $1 looks like a git URL/shorthand rather than a bare OCA module
# name: OCA module names are Python identifiers and never contain '/', so
# this is a zero-collision-risk split from the existing arg-as-module-name
# path.
oca_url_shaped() {
  case "$1" in
    *://*|git@*|*.git|*/*) return 0 ;;
    *) return 1 ;;
  esac
}

# Resolve $1 (a full git URL, or "owner/repo" GitHub shorthand) to a full git
# URL, printed on stdout. Any string with a scheme (://) or an scp-style
# git@ prefix is passed through to git verbatim -- any host, not just
# GitHub. Only an unambiguous, scheme-less "owner/repo" (exactly one slash)
# is expanded as GitHub shorthand; anything else that still looked
# url-shaped (e.g. a bare host/path with a forgotten scheme) is rejected
# rather than silently guessed at.
oca_resolve_git_url() {
  local arg="$1"
  case "$arg" in
    *://*|git@*) printf '%s\n' "$arg"; return 0 ;;
  esac
  case "$arg" in
    */*/*|*/) : ;;                                  # 2+ slashes / trailing slash: not owner/repo
    */*) printf 'https://github.com/%s.git\n' "${arg%.git}"; return 0 ;;
  esac
  echo "not a full git URL and not 'owner/repo' shorthand: $arg" >&2
  return 1
}

# Derive a submodule folder slug from a resolved URL: strip a trailing
# .git, take the last path segment. Works for both URL and scp-style
# (git@host:owner/repo) forms since both end in /repo.
oca_repo_slug() {
  local u="${1%.git}"
  u="${u%/}"
  printf '%s\n' "${u##*/}"
}

# Detect $1's default branch via `ls-remote --symref ... HEAD`. Prints the
# branch name, or nothing if the remote is unreachable / has no HEAD (the
# caller decides how to handle that). `|| true`: an unreachable remote must
# not trip `set -e` in a plain assignment context.
oca_default_branch() {
  local url="$1" ref
  ref="$(git ls-remote --symref "$url" HEAD 2>/dev/null | awk '/^ref:/ {print $2}')" || true
  printf '%s\n' "${ref#refs/heads/}"
}

# Scan one already-cloned path for Odoo modules: either the repo itself is
# one module (manifest at its root), or it holds several module dirs
# (manifest one level down) -- the same two shapes lib/oca_sources.py's
# _local_modules() globs for, scoped to this one path instead of a full
# modules/* sweep. Prints bare module (directory) names, one per line; no
# manifest content is parsed, only presence of __manifest__.py.
oca_scan_modules() {
  local path="$1" f
  for f in "$path"/__manifest__.py; do
    [ -e "$f" ] && basename "$path"
  done
  for f in "$path"/*/__manifest__.py; do
    [ -e "$f" ] || continue
    basename "$(dirname "$f")"
  done
}

# Present bare names (one per line on stdin) in a gum multi-select with
# NOTHING pre-selected -- an accidental Enter must not silently claim all of
# them. Prints the chosen names, one per line. Mirrors oca_pick_bundles'
# `gum choose --no-limit` shape; no JSON metadata to decorate labels with
# here, so raw names are used directly.
oca_pick_from_list() {
  local header="$1"
  gum choose --no-limit --header "$header" || true
}

# Present ALL installable modules for a series in a fuzzy gum picker; print the
# chosen bare module names. The `application` flag is only a hint (★) — most
# useful OCA modules (localizations, feature modules like repair_*) are not
# flagged as applications but are installed directly. Applications sort first.
# A TAB-separated module<TAB>label table lets us map the decorated label back to
# the bare module name. gum filter handles the ~2,500-row list with fuzzy search.
oca_pick_modules() {
  local series="$1"
  local rows
  rows="$(jq -r --arg s "$series" '
      [ .[] | select(.installable == true and (.version | startswith($s + "."))) ]
      | sort_by([(.application | not), .repo, .module])[]
      | "\(.module)\t\(if .application then "★" else " " end) \(.module)  ·  \(.repo)  ·  \((.summary // "") | gsub("\\s+"; " ") | .[0:60])"
    ' "$OCA_DATASET")"
  [ -z "$rows" ] && { echo "No installable modules for series $series." >&2; return 0; }
  local chosen
  # --no-fuzzy: match from the start of a word (predictable prefix matching)
  # instead of the loose default subsequence fuzzing. Typing a repo name (e.g.
  # "repair") surfaces all that repo's modules via the repo column.
  chosen="$(cut -f2 <<<"$rows" \
    | gum filter --no-limit --height 20 --no-fuzzy \
        --placeholder "type a module or repo name (★ = application)" \
        --header "Select OCA modules for $series  (Tab to select, Enter to confirm):" || true)"
  while IFS= read -r lbl; do
    [ -z "$lbl" ] && continue
    awk -F'\t' -v l="$lbl" '$2 == l { print $1 }' <<<"$rows"
  done <<<"$chosen"
}

# ── bundles ────────────────────────────────────────────────────────────────
# Curated, hand-maintained named sets of "must-have" module names, defined in
# data/oca-bundles.json. Requires OCA_BUNDLES to point at that file (both the
# scaffolder and `odoo module add-bundle` bake the store path into it).

oca_bundle_names() { jq -r 'keys[]' "$OCA_BUNDLES"; }

# Interactively choose bundles; print the chosen bare bundle names.
# A TAB-separated name<TAB>label table maps the decorated label back to the key.
oca_pick_bundles() {
  local rows chosen
  rows="$(jq -r 'to_entries[]
    | "\(.key)\t\(.key)  —  \(.value.label)  (\(.value.modules | length) modules)"' "$OCA_BUNDLES")"
  [ -z "$rows" ] && { echo "No bundles defined." >&2; return 0; }
  chosen="$(cut -f2 <<<"$rows" \
    | gum choose --no-limit \
        --header "Select OCA bundle(s) (space=toggle, enter=confirm):" || true)"
  while IFS= read -r lbl; do
    [ -z "$lbl" ] && continue
    awk -F'\t' -v l="$lbl" '$2 == l { print $1 }' <<<"$rows"
  done <<<"$chosen"
}

# Expand bundle names to their union of module names, scoped to one series.
# Bundles are series-blind, so members with no in-series catalog record are
# dropped with a warning rather than recorded and left to fail at install time.
# Prints the deduped, sorted module names (one per line).
oca_expand_bundles() {
  local series="$1"; shift
  local names=("$@") wanted=() n m
  for n in "${names[@]}"; do
    [ -z "$n" ] && continue
    if ! jq -e --arg n "$n" 'has($n)' "$OCA_BUNDLES" >/dev/null; then
      echo "  ⚠  unknown bundle: $n   (available: $(oca_bundle_names | tr '\n' ' '))" >&2
      continue
    fi
    while IFS= read -r m; do
      [ -n "$m" ] && wanted+=("$m")
    done < <(jq -r --arg n "$n" '.[$n].modules[]' "$OCA_BUNDLES")
  done
  [ "${#wanted[@]}" -eq 0 ] && return 0

  # Partition against the in-series catalog.
  local wanted_json
  wanted_json="$(printf '%s\n' "${wanted[@]}" | jq -R . | jq -s 'unique')"
  local missing
  missing="$(jq -r --arg s "$series" --argjson want "$wanted_json" '
      ([ .[] | select(.version | startswith($s + ".")) | .module ] | unique) as $have
      | $want - $have | .[]' "$OCA_DATASET")"
  if [ -n "$missing" ]; then
    echo "  ⚠  not available for $series, skipped: $(tr '\n' ' ' <<<"$missing")" >&2
  fi
  jq -r --arg s "$series" --argjson want "$wanted_json" '
      ([ .[] | select(.version | startswith($s + ".")) | .module ] | unique) as $have
      | [ $want[] | select(. as $m | $have | index($m)) ] | .[]' "$OCA_DATASET"
}
