# Python environment factory for Odoo + OCA projects.
#
# Builds the environment from a uv project (pyproject.toml + uv.lock) via uv2nix.
# OCA modules are modern `whool` packages (`odoo-addon-<module>`) and OCB is an
# editable `odoo` dependency, all declared as editable [tool.uv.sources] path
# deps (generated by lib/oca_sources.py). uv resolves the entire dependency
# graph — every module's `external_dependencies.python` plus Odoo's own
# requirements — so there is no custom aggregation. The env installs the modules
# editable (referencing $REPO_ROOT), so source edits are live.
#
# Usage:
#   import ./lib/python.nix {
#     inherit pkgs lib python projectName workspaceRoot;
#     pyproject-nix = inputs.pyproject-nix;
#     pyproject-build-systems = inputs.pyproject-build-systems;
#     uv2nix = inputs.uv2nix;
#     extraOverrides = final: prev: { ... };
#   }

{
  pkgs,
  lib,
  python,
  workspaceRoot,
  projectName,
  pyproject-nix,
  pyproject-build-systems,
  uv2nix,
  pythonLibraries ? { },
  extraOverrides ? (_final: _prev: { }),
}:

let
  workspace = uv2nix.lib.workspace.loadWorkspace { inherit workspaceRoot; };

  rootPyproject = builtins.fromTOML (builtins.readFile (workspaceRoot + "/pyproject.toml"));
  rootPkgName = rootPyproject.project.name;

  overlay = workspace.mkPyprojectOverlay {
    sourcePreference = "wheel";
  };

  # OCB's build backend (pep517_odoo) is vendored in ./setup and referenced via
  # `backend-path = ["setup"]`. pyproject-nix's build doesn't add it to sys.path,
  # so make it importable during odoo's wheel build.
  odooBackendOverlay = _final: prev: {
    odoo = prev.odoo.overrideAttrs (old: {
      preBuild = (old.preBuild or "") + ''
        export PYTHONPATH="$PWD/setup''${PYTHONPATH:+:$PYTHONPATH}"
      '';
    });
  };

  # lxml.html.clean was split out of lxml (>=5.2) into a standalone
  # lxml_html_clean package. odoo/_monkeypatches/lxml.py imports it
  # unconditionally at every Odoo startup, but OCB's setup.py -- through at
  # least the 18.0 series -- never lists it in install_requires (only its
  # requirements.txt does, which uv2nix does not read), so uv resolves
  # whatever lxml is newest on PyPI and the import fails. Backfill it from
  # nixpkgs. A series whose setup.py already declares it (19.0+) is left
  # alone: `prev` already carries the uv-resolved attribute there.
  lxmlHtmlCleanOverlay =
    final: prev:
    lib.optionalAttrs (!(prev ? lxml_html_clean)) (
      let
        base = python.pkgs.lxml-html-clean;
        # nixpkgs' own `passthru.dependencies` is a flat derivation list that
        # FEEDS its build (mk-python-derivation.nix folds it into
        # propagatedBuildInputs) -- overriding it via overrideAttrs would
        # re-derive that build from the wrong shape. pyproject-nix's venv
        # resolver (build/lib/resolvers.nix) instead reads
        # `pkg.passthru.dependencies` post-build, as an attrset
        # (`{ name = [ extras ]; }`), to walk the closure. So just relabel
        # the metadata on the already-built derivation value (a plain
        # attrset merge, no rebuild) rather than overrideAttrs. Its only
        # runtime dependency is lxml itself, already resolved in the set.
        pyprojectMeta = {
          dependencies = { lxml = [ ]; };
          optional-dependencies = { };
        };
      in
      {
        lxml_html_clean = base // pyprojectMeta // {
          passthru = (base.passthru or { }) // pyprojectMeta;
        };
      }
    );

  # Declarative native-library exposure: for each `<python package> = [ libs ]`,
  # add the libs' headers (their `.dev` output) + pkg-config to that package's
  # build, and the libs to its buildInputs. Lets a C-extension dep (e.g. pycups
  # -> cups, python-snappy -> snappy) build without a bespoke override.
  pythonLibsOverlay = final: prev:
    builtins.mapAttrs (
      name: libs:
      prev.${name}.overrideAttrs (old: {
        nativeBuildInputs =
          (old.nativeBuildInputs or [ ])
          ++ [ final.setuptools pkgs.pkg-config ]
          ++ lib.concatMap (l: lib.optional (l ? dev) l.dev) libs;
        buildInputs = (old.buildInputs or [ ]) ++ libs;
      })
    ) (lib.filterAttrs (name: _: prev ? ${name}) pythonLibraries);

  pythonSet =
    (pkgs.callPackage pyproject-nix.build.packages {
      inherit python;
    }).overrideScope
      (
        lib.composeManyExtensions [
          pyproject-build-systems.overlays.default
          overlay
          odooBackendOverlay
          pythonLibsOverlay
          lxmlHtmlCleanOverlay
          extraOverrides
        ]
      );

  # Editable overlay (DEV): local path-source packages (every OCA module) install
  # editable, resolving against $REPO_ROOT at runtime so source edits are live.
  editableSet = pythonSet.overrideScope (
    workspace.mkEditablePyprojectOverlay { root = "$REPO_ROOT"; }
  );

  # For the virtual single-root project, `workspace.deps.default` is the root
  # node; mkVirtualEnv resolves its deps (odoo + the install roots) with markers.

  # Force lxml_html_clean into the venv regardless of what the workspace lock
  # resolved (see lxmlHtmlCleanOverlay above) -- a no-op where it's already
  # there, since the package declares no extras.
  withLxmlHtmlClean = deps: deps // { lxml_html_clean = deps.lxml_html_clean or [ ]; };

  # Production: real wheels for odoo + all modules — self-contained (no
  # $REPO_ROOT), for builtOdoo / containers / NixOS.
  odooPythonEnv = pythonSet.mkVirtualEnv "${projectName}-odoo-env" (
    withLxmlHtmlClean workspace.deps.default
  );

  # Development: modules installed editable (+ dev-group tools), live source.
  devPythonEnv = editableSet.mkVirtualEnv "${projectName}-odoo-dev-env" (
    withLxmlHtmlClean (workspace.deps.default // workspace.deps.groups)
  );
in
{
  inherit
    pythonSet
    editableSet
    odooPythonEnv
    devPythonEnv
    workspace
    rootPyproject
    rootPkgName
    ;
}
