# Build-time artifacts for the secrets subsystem: the generated agenix rules
# file, the recipient checker, and the pieces lib/scripts.nix needs to render
# `edit-secret` / `rekey-secrets`.
#
# Split out of modules/secrets.nix because that module is top-level, where
# `pkgs` does not exist. Split out of lib/scripts.nix so the derivations are
# built once rather than per-script.
{
  lib,
  pkgs,
  cfg,
  schema,
}:

let
  enabled = cfg.enable or false;

  # ragenix, not ryantm/agenix: it is in nixpkgs (so no new flake input), it is
  # a drop-in — same RULES env var, same -e/-r/-d/-i — and it ships an `agenix`
  # symlink so muscle memory and any existing docs still work. Taking the real
  # agenix as an input would drag nix-darwin and home-manager into every
  # consumer's lock, because its outputs destructure them positionally and they
  # therefore cannot be followed away.
  cli = pkgs.ragenix;

  # The declared recipients, as JSON: { "<repo-relative .age path>": [key…] }.
  # Everything else is derived from this — the checker reads it directly, and
  # the rules file agenix reads is rendered from it at runtime (below).
  rulesJSON = pkgs.writeText "odoo-nix-secrets.json" (schema.rulesJSON cfg);

  # Shell snippet: write an agenix rules file to $RULES, with **absolute** paths.
  #
  # It cannot be a store file with repo-relative keys, which is the obvious
  # design and was the first one tried. ragenix resolves a rule key relative to
  # the *rules file's own directory* — so a store-path RULES turns
  # "secrets/backup-access.age" into "/nix/store/secrets/backup-access.age",
  # which does not exist. `agenix -e` then reports no rule for the file, and
  # `agenix -r` skips it as "does not exist, ignored" and exits 0, so a rekey
  # silently does nothing at all.
  #
  # (ryantm/agenix resolves the same key against $PWD instead. Absolute paths
  # are correct for both, which is the other reason to render them.)
  #
  # Rendered at runtime because the worktree path is not knowable at eval time:
  # a flake sees its own source as a store path. The script has it as
  # $REPO_ROOT — the git worktree.
  writeRules = ''
    __fnx_rules_dir="$(mktemp -d)"
    trap 'rm -rf "$__fnx_rules_dir"' EXIT
    RULES="$__fnx_rules_dir/secrets.nix"
    export RULES
    ${pkgs.jq}/bin/jq -r --arg root "$REPO_ROOT" '
      "# Generated by odoo-nix. Do not edit; do not commit.",
      "{",
      (to_entries[] | "  " + ($root + "/" + .key | @json) + ".publicKeys = ["
        + ([.value[] | @json] | join(" ")) + "];"),
      "}"
    ' ${rulesJSON} > "$RULES"
  '';

  agecheck = pkgs.writeTextFile {
    name = "odoo-nix-agecheck";
    destination = "/bin/odoo-nix-agecheck";
    executable = true;
    # Not writers.writePython3Bin: it runs its own linter with its own opinions
    # at build time. A shebang'd text file is dependency-free and stable — the
    # same reasoning as lib/workspace-tool.nix.
    text = "#!${pkgs.python3}/bin/python3\n" + builtins.readFile ./agecheck.py;
  };

  # `setup-backup-access` — five prompts instead of five variable names and the
  # quoting rules for a file the shell will source. `fetch` is the standalone
  # remote tool (lib/odoo_nix_cli/remote.py) used to test the credentials.
  #
  # A writeShellApplication rather than a devenv script body so shellcheck sees
  # it (devenv never lints those) and so the baked paths are resolved once. It
  # is offered only when the project declares the backup-access secret; there is
  # nothing to prompt for otherwise.
  setupBackupAccess =
    fetch:
    pkgs.writeShellApplication {
      name = "odoo-nix-setup-backup-access";
      runtimeInputs = with pkgs; [
        gum
        git
        gnused
        coreutils
        gnugrep
        cli
        # For reading an existing secret back: ragenix implements only
        # --edit/--rekey/--schema, so there is no `agenix -d`.
        rage
      ];
      text = ''
        AGENIX=${lib.getExe' cli "agenix"}
        AGECHECK=${lib.getExe' agecheck "odoo-nix-agecheck"}
        RULES_JSON=${rulesJSON}
        SECRET_REL="${cfg.relDir}/backup-access.age"
        FETCH=${fetch}
        # Assigned rather than interpolated into the loop: these are shell
        # strings holding $HOME, so they expand here and nowhere else.
        IDENTITY_PATHS="${toString cfg.identityPaths}"

        write_rules() {
          ${writeRules}
        }
      ''
      + builtins.readFile ./sh/backup-access.sh;
    };

  # Shell fragment: decrypt every declared secret and make it usable.
  #
  # Sourced on demand by the scripts that need it, NOT from enterShell. Three
  # reasons, all load-bearing:
  #
  #   1. agenix-shell rm -rf's its runtime dir and re-runs rage on every source,
  #      and enterShell runs on every direnv reload — so a passphrase-protected
  #      key would prompt on every file save.
  #   2. agenix-shell exports the plaintext itself, not just the path. At shell
  #      entry that puts credentials in the environment of every process in the
  #      session, `devenv up`'s children included, readable through
  #      /proc/<pid>/environ.
  #   3. A decryption failure becomes an error where the secret is used, with a
  #      message that can say what to do, instead of a warning scrolled past
  #      several minutes earlier.
  loadSecrets =
    installationScript:
    let
      envSecrets = builtins.filter (s: s.format == "env") cfg.declared;
    in
    ''
      # agenix-shell hardcodes "$XDG_RUNTIME_DIR/agenix-shell/<hash>" with no
      # fallback (devenv has one; agenix-shell does not). Unset — the normal
      # state on darwin — that path becomes "/agenix-shell/…", every decrypt
      # fails, and because nothing here runs under `set -e` it fails silently.
      if [ -z "''${XDG_RUNTIME_DIR:-}" ]; then
        XDG_RUNTIME_DIR="''${DEVENV_RUNTIME:-''${TMPDIR:-/tmp}/odoo-nix-$UID}"
        export XDG_RUNTIME_DIR
        mkdir -p "$XDG_RUNTIME_DIR"
      fi

      # The installation script is built with bashOptions = [], so it does not
      # touch our shell options — but a failing `rage` still returns non-zero
      # and would trip our own `set -e`. Decryption failure is diagnosed below,
      # properly; it must not abort here.
      __fnx_errexit=0
      case "$-" in *e*) __fnx_errexit=1; set +e ;; esac
      # shellcheck source=/dev/null
      . "${lib.getExe installationScript}"
      [ "$__fnx_errexit" = 1 ] && set -e
      unset __fnx_errexit

      ${lib.concatMapStringsSep "\n" (s: ''
        if [ -r "''${${s.var}_PATH:-/nonexistent}" ]; then
          set -a
          # shellcheck source=/dev/null
          . "''$${s.var}_PATH"
          set +a
        fi
      '') envSecrets}
    '';

  # Shell fragment: fail with something actionable when a secret is empty.
  requireSecret = var: ''
    if [ -z "''${${var}:-}" ]; then
      echo "odoo-nix: could not decrypt the '${var}' secret." >&2
      echo >&2
      ${lib.getExe' agecheck "odoo-nix-agecheck"} explain ${rulesJSON} "${var}" \
        --root "$REPO_ROOT" >&2 || true
      exit 3
    fi
  '';
in
{
  inherit
    enabled
    cli
    writeRules
    rulesJSON
    setupBackupAccess
    agecheck
    loadSecrets
    requireSecret
    ;

  inherit (cfg) declared relDir;

  # Packages the dev shell needs once secrets are on.
  packages = lib.optionals enabled [
    cli
    agecheck
    pkgs.jq
  ];

  # Every declared secret, as `<name> — <purpose>` lines for `edit-secret`'s
  # usage text. The name is what the user passes; it is the .age path with the
  # secrets dir and the extension stripped.
  names = map (s: {
    name = lib.removeSuffix ".age" (lib.removePrefix "${cfg.relDir}/" s.relPath);
    inherit (s) relPath format var;
  }) cfg.declared;
}
